// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-invoices.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sbForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_invoices_default = defineTool({
  name: "list_invoices",
  title: "List invoices",
  description: "Lists invoices in the signed-in user's household, most recent first. Amounts are in EUR.",
  inputSchema: {
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50)."),
    only_unpaid: z.boolean().optional().describe("If true, return only unpaid invoices."),
    kostengruppe_prefix: z.string().optional().describe("Filter by DIN 276 cost-group code prefix, e.g. '3' or '310'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, only_unpaid, kostengruppe_prefix }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sbForUser(ctx).from("invoices").select("id, company_name, invoice_number, invoice_date, amount, net_amount, tax_amount, is_gross, is_paid, status, kostengruppe_code, description").order("invoice_date", { ascending: false }).limit(limit ?? 50);
    if (only_unpaid) q = q.eq("is_paid", false);
    if (kostengruppe_prefix) q = q.like("kostengruppe_code", `${kostengruppe_prefix}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { invoices: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-offers.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sbForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_offers_default = defineTool2({
  name: "list_offers",
  title: "List offers",
  description: "Lists contractor offers in the signed-in user's household. Amounts are in EUR.",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sbForUser2(ctx).from("offers").select("id, title, company_name, offer_date, total_amount, is_gross, notes").order("offer_date", { ascending: false, nullsFirst: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { offers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-estimate-versions.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
function sbForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_estimate_versions_default = defineTool3({
  name: "list_estimate_versions",
  title: "List estimate versions",
  description: "Lists all cost-estimate versions (V1, V2, ...) in the household with their blocks.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = sbForUser3(ctx);
    const { data: versions, error: vErr } = await sb.from("estimate_versions").select("id, name, version_number, is_active, created_at, notes").order("version_number", { ascending: true });
    if (vErr) return { content: [{ type: "text", text: vErr.message }], isError: true };
    const { data: blocks, error: bErr } = await sb.from("estimate_blocks").select("id, version_id, label, block_type, carry_forward, sort_order, processed");
    if (bErr) return { content: [{ type: "text", text: bErr.message }], isError: true };
    const result = (versions ?? []).map((v) => ({
      ...v,
      blocks: (blocks ?? []).filter((b) => b.version_id === v.id).sort((a, b) => a.sort_order - b.sort_order)
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: { versions: result }
    };
  }
});

// src/lib/mcp/tools/budget-summary.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sbForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var budget_summary_default = defineTool4({
  name: "budget_summary",
  title: "Budget summary (target vs actual)",
  description: "Returns target (from the active estimate version) vs actual (sum of invoices) per DIN 276 3-digit cost group. Amounts in EUR.",
  inputSchema: {
    version_id: z3.string().uuid().optional().describe("Estimate version to use as target. Defaults to the active version.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ version_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = sbForUser4(ctx);
    let versionId = version_id;
    if (!versionId) {
      const { data: v } = await sb.from("estimate_versions").select("id").eq("is_active", true).limit(1).maybeSingle();
      versionId = v?.id;
    }
    const targets = {};
    if (versionId) {
      const { data: blocks } = await sb.from("estimate_blocks").select("id").eq("version_id", versionId);
      const blockIds = (blocks ?? []).map((b) => b.id);
      if (blockIds.length) {
        const { data: items } = await sb.from("architect_estimate_items").select("kostengruppe_code, estimated_amount").in("block_id", blockIds);
        for (const it of items ?? []) {
          const key = (it.kostengruppe_code ?? "").substring(0, 3);
          targets[key] = (targets[key] ?? 0) + Number(it.estimated_amount ?? 0);
        }
      }
    }
    const actuals = {};
    const { data: invs } = await sb.from("invoices").select("amount, kostengruppe_code");
    for (const inv of invs ?? []) {
      const key = (inv.kostengruppe_code ?? "").substring(0, 3) || "uncategorized";
      actuals[key] = (actuals[key] ?? 0) + Number(inv.amount ?? 0);
    }
    const keys = Array.from(/* @__PURE__ */ new Set([...Object.keys(targets), ...Object.keys(actuals)])).sort();
    const rows = keys.map((k) => ({
      kostengruppe: k,
      target_eur: Math.round((targets[k] ?? 0) * 100) / 100,
      actual_eur: Math.round((actuals[k] ?? 0) * 100) / 100,
      delta_eur: Math.round(((actuals[k] ?? 0) - (targets[k] ?? 0)) * 100) / 100
    }));
    const totals = rows.reduce(
      (a, r) => ({ target: a.target + r.target_eur, actual: a.actual + r.actual_eur }),
      { target: 0, actual: 0 }
    );
    return {
      content: [{ type: "text", text: JSON.stringify({ version_id: versionId, rows, totals }, null, 2) }],
      structuredContent: { version_id: versionId, rows, totals }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yrcxqyadtftveuzbjiup";
var mcp_default = defineMcp({
  name: "baukosten-mcp",
  title: "Baukosten Tracker",
  version: "0.1.0",
  instructions: "Read-only access to the signed-in user's household construction-cost data: invoices, offers, DIN 276 cost estimates (versioned with blocks), and a target-vs-actual budget summary. Amounts are in EUR.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_invoices_default, list_offers_default, list_estimate_versions_default, budget_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
